export const fetch = require("node-fetch");


export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_ALL_BY_NAME = "GET_ALL_BY_NAME";
export const GET_ALL_GENRES = "GET_ALL_GENRES";
export const GET_DETAILS = "GET_DETAILS";
export const GET_PLATFORMS = "GET_PLATFORMS";
export const POST_GAME = "POST_GAME";

export const PREV_PAGE = "PREV_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const ON_SPECIFIC_PAGE = "ON_SPECIFIC_PAGE";
export const SET_AUX_PAGINATE = "SET_AUX_PAGINATE";
export const SET_PAGES = "SET_PAGES";
export const SET_SUBPAGES = "SET_SUBPAGES";
export const PREV_SUBPAGE = "PREV_SUBPAGE";
export const NEXT_SUBPAGE = "NEXT_SUBPAGE";
export const SET_PREVPIVOT = "SET_PREVPIVOT";
export const SET_NEXTPIVOT = "SET_NEXTPIVOT";

export const RESET_GAMES_TO_RENDER = "RESET_GAMES_TO_RENDER";
export const RESET_INPUT_ORDER = "RESET_INPUT_ORDER ";
export const RESET_INPUT_FILTER_BY_GENRE = "RESET_INPUT_FILTER_BY_GENRE";
export const RESET_INPUT_FILTER_BY_CREATION = "RESET_INPUT_FILTER_BY_CREATION";
export const RESET_GAMES_BY_NAME = "RESET_GAMES_BY_NAME";
export const RESET_DETAIL_GAME="RESET_DETAIL_GAME"
export const RESET_FETCHING = "RESET_FETCHING";
export const RESET_SOME_APPLIED_FILTER_FLAG = "RESET_SOME_APPLIED_FILTER_FLAG";
export const RESET_INPUT_SEARCHBAR = "RESET_INPUT_SEARCHBAR";
export const RESET_AXIOS_FLAG="RESET_AXIOS_FLAG";
export const RESET_PAGINATE="RESET_PAGINATE";
export const CLEAN_GAMES_TO_RENDER = "CLEAN_GAMES_TO_RENDER";

export const SET_INPUT_SEARCHBAR = "SET_INPUT_SEARCHBAR";
export const SET_INPUT_FILTER_BY_GENRE = "SET_INPUT_FILTER_BY_GENRE";
export const SET_INPUT_FILTER_BY_CREATION = "SET_INPUT_FILTER_BY_CREATION";
export const SET_INPUT_ORDER = "SET_INPUT_ORDER";
export const SET_BY_NAME = "SET_BY_NAME";
export const SET_FLAG_SOME_FILTER_APPLIED = "SET_FLAG_SOME_FILTER_APPLIED";

export const FILTER_BY_GENRES = "FILTER_BY_GENRES";
export const FILTER_BY_CREATION = "FILTER_BY_CREATION";

export const ORDER_BY = "ORDER_BY";
